name: RPGskills

version: 1.0

main: io.github.chw3021.rmain.RMain

commands:
   rpg:
      description: plugin
   party:
      description: plugin
   smith:
      description: plugin
        
api-version: 1.21